### PR TITLE
Fix README Path for PKHeX.Core

### PR DESCRIPTION
**Pull request by pifopi**
Hello !

A small fix to the readme I found while updating my setup

### CODE REVIEW

**Comment by Lusamine** [comment]
I wrote it this way because both of my paths include `net7.0-windows`. This change would make it incorrect for me. What are you using to build these programs?

**Comment by pifopi** [comment]
Oh ? On my side they're both without. I'm using visual 2022 Version 17.4.4 (and windows 10 but that shouldn't matter)

**Comment by Koi-3088** [comment]
`PKHeX.Core.dll` path should look like this since it targets `net7.0`.
image

`AutoModPlugins.dll` path should look like this since it targets `net7.0-windows`.
image

**Comment by pifopi** [comment]
Indeed, I changed the two paths while only one was needed. My bad and let me fix it !

**Comment by Lusamine** [comment]
I usually grab mine out of WinForms which was why I had the `-windows` suffix. This looks okay now.

**Pull request merged**
