### PR TITLE
Fix for infinite loop with static variable

### PR DESCRIPTION
**Pull request by pifopi**
Hello !

Anubis kindly told me about this issue as I was investigating why it wasn't connecting on my side. Here is my take on a possible fix. I do not think it is very elegant but it does work. Feel free to accept or reject !

Thanks

### CODE REVIEW

**Comment by Koi-3088** [comment]
Have you tested changing a box? It resets the box for me.

**Comment by pifopi** [comment]
It indeed works weirdly. It does still switch to the new box but come back to box 1. (first time it does 1->2->1 Second time 1->3->1)
It's late for me now but i'll probably have some time to look into it tomorrow

**Comment by pifopi** [comment]
Oh, is there any task thread of anything? Delaying such change in a task thread could also fix the issue. First call, it would do just like now. But second call, it wouldn't trigger a box change anymore?

**Comment by Koi-3088** [comment]
During my testing I had locks in place, and had decorated the method with `[STAThread]`. No dice. Currently selected box index is set internally, and, as such, we don't have enough data to work with in order to properly get around this issue by purely working with ALM, unless I've missed something obvious.

**Pull request closed without merging**
