### PR TITLE
Add optional prompts for smogon imports

### PR DESCRIPTION
**Pull request by soopercool101**
Old behavior:
Gather all sets for a given pokemon, import them all immediately via the showdown import function
If there is only one set, the importer asks to confirm before adding it to the tabs
If there is more than one set, the importer imports to boxes without user input

New proposed behavior:
Gather all sets for a given pokemon, prompt user for importing for each (include format and name for these sets)
If only one set is imported, the importer moves it to the tabs immediately without asking again
If more than one set are imported, they are imported to boxes without further input
If no sets are imported, don't import anything

Not sure if this behavior is better or not so I'm flagging this one as a draft

### CODE REVIEW

**Comment by Lusamine** [comment]
> prompt user for importing for each (include format and name for these sets)

This immediately strikes me as obnoxious when it's easier for me to clear out the ones I don't want or make manual edits, as opposed to approving every single import.

**Comment by soopercool101** [comment]
Tested with a mon with a notable number of sets, Corviknight:

Here's standard navigation of the prompts: https://gfycat.com/FakeTerrificApisdorsatalaboriosa
They can somewhat be skipped by holding enter: https://gfycat.com/ShorttermMajorBlackandtancoonhound

Thinking of making this an option menu thing, not sure it's good enough for default behavior

**Comment by architdate** [comment]
Hmm, Yes, please have this as a setting instead of the default behavior (set default to not prompt). For stuff like landorus in gen 7, there would be like 30 boxes to click through!

**Comment by architdate** [comment]
Does `skipDialog = true` actually skip the dialog? Seems like skipDialog true will prompt the dialog everytime right?

Is the variable name right?

**Comment by soopercool101** [comment]
`SkipDialog = true` skips the dialog box. The if statement is set up to ensure that the second half of the && won't activate without doing an autoreturn

**Comment by soopercool101** [comment]
Flow for single-pokemon input (identical to the old flow except now includes set title):
https://gfycat.com/AmpleWiltedAnemone

**Comment by architdate** [comment]
Ah makes sense now. My bad. Code looks all good to me

**Pull request merged**
